# Generated by Django 5.2.5 on 2026-02-25 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentArchive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_record_id", models.IntegerField(verbose_name="原记录ID")),
                ("record_no", models.CharField(max_length=32, verbose_name="支付单号")),
                ("order_no", models.CharField(max_length=32, verbose_name="订单号")),
                ("pay_type", models.CharField(max_length=20, verbose_name="支付方式")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="支付金额"
                    ),
                ),
                ("status", models.CharField(max_length=20, verbose_name="支付状态")),
                (
                    "platform_trade_no",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="第三方交易号"
                    ),
                ),
                (
                    "pay_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="支付时间"
                    ),
                ),
                ("created_at", models.DateTimeField(verbose_name="原创建时间")),
                (
                    "archived_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="归档时间"),
                ),
            ],
            options={
                "verbose_name": "支付归档",
                "verbose_name_plural": "支付归档",
                "ordering": ["-archived_at"],
            },
        ),
        migrations.AddField(
            model_name="paymentrecord",
            name="archived",
            field=models.BooleanField(default=False, verbose_name="已归档"),
        ),
        migrations.CreateModel(
            name="RefundRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "refund_no",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="退款单号"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="退款金额"
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="退款原因")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "退款中"),
                            ("success", "退款成功"),
                            ("failed", "退款失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="退款状态",
                    ),
                ),
                (
                    "platform_refund_no",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="第三方退款号"
                    ),
                ),
                (
                    "refund_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="退款时间"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refunds",
                        to="payments.paymentrecord",
                        verbose_name="原支付记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "退款记录",
                "verbose_name_plural": "退款记录",
                "ordering": ["-created_at"],
            },
        ),
    ]
