# Generated by Django 5.2.5 on 2026-03-06 14:47

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmethod",
            name="account_mask",
            field=models.CharField(blank=True, max_length=100, verbose_name="账号掩码"),
        ),
        migrations.AddField(
            model_name="user",
            name="is_locked",
            field=models.BooleanField(default=False, verbose_name="是否锁定"),
        ),
        migrations.AddField(
            model_name="user",
            name="last_login_ip",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="最后登录IP"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="locked_until",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="锁定截止时间"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="login_failed_count",
            field=models.PositiveIntegerField(default=0, verbose_name="登录失败次数"),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="account",
            field=users.models.EncryptedField(max_length=255, verbose_name="账号标识"),
        ),
        migrations.AlterField(
            model_name="user",
            name="id_card",
            field=users.models.EncryptedField(
                blank=True, max_length=255, null=True, verbose_name="身份证号"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=users.models.EncryptedField(
                max_length=255, unique=True, verbose_name="手机号"
            ),
        ),
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP地址")),
                (
                    "username",
                    models.CharField(blank=True, max_length=150, verbose_name="用户名"),
                ),
                (
                    "attempted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="尝试时间"),
                ),
                (
                    "is_successful",
                    models.BooleanField(default=False, verbose_name="是否成功"),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="用户代理")),
            ],
            options={
                "verbose_name": "登录尝试",
                "verbose_name_plural": "登录尝试",
                "ordering": ["-attempted_at"],
                "indexes": [
                    models.Index(
                        fields=["ip_address", "attempted_at"],
                        name="users_login_ip_addr_bed342_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SecurityAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "登录"),
                            ("login_failed", "登录失败"),
                            ("logout", "登出"),
                            ("password_change", "密码修改"),
                            ("payment", "支付"),
                            ("refund", "退款"),
                            ("data_export", "数据导出"),
                            ("sensitive_operation", "敏感操作"),
                        ],
                        max_length=50,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="用户代理")),
                (
                    "details",
                    models.JSONField(blank=True, default=dict, verbose_name="详细信息"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="时间戳"),
                ),
                (
                    "is_suspicious",
                    models.BooleanField(default=False, verbose_name="是否可疑"),
                ),
                (
                    "risk_level",
                    models.CharField(
                        default="low", max_length=20, verbose_name="风险等级"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "安全审计日志",
                "verbose_name_plural": "安全审计日志",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "action"], name="users_secur_user_id_a517c3_idx"
                    ),
                    models.Index(
                        fields=["timestamp"], name="users_secur_timesta_3f6d89_idx"
                    ),
                    models.Index(
                        fields=["is_suspicious"], name="users_secur_is_susp_badac0_idx"
                    ),
                ],
            },
        ),
    ]
