# Generated by Django 5.2.5 on 2025-09-02 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_stock",
                    models.PositiveIntegerField(default=0, verbose_name="当前库存"),
                ),
                (
                    "alarm_threshold",
                    models.PositiveIntegerField(default=5, verbose_name="预警阈值"),
                ),
                (
                    "last_checked",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后盘点时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="products.product",
                        verbose_name="商品",
                    ),
                ),
            ],
            options={
                "verbose_name": "库存",
                "verbose_name_plural": "库存",
            },
        ),
    ]
