# Generated by Django 5.2.5 on 2025-09-02 21:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="商品名称")),
                ("description", models.TextField(blank=True, verbose_name="商品描述")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="单价"
                    ),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(default=0, verbose_name="实际库存"),
                ),
                (
                    "locked_stock",
                    models.PositiveIntegerField(default=0, verbose_name="锁定库存"),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="例如：A1、B3", max_length=20, verbose_name="货道位置"
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="products/", verbose_name="商品图片"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否在售"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "商品",
                "verbose_name_plural": "商品",
                "ordering": ["location"],
            },
        ),
        migrations.CreateModel(
            name="VisualRecognitionRecord",
            fields=[
                (
                    "record_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="记录ID",
                    ),
                ),
                (
                    "image_path",
                    models.CharField(max_length=255, verbose_name="图像路径"),
                ),
                (
                    "algorithm_used",
                    models.CharField(max_length=50, verbose_name="使用算法"),
                ),
                (
                    "recognition_result",
                    models.JSONField(null=True, verbose_name="识别结果"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "识别中"),
                            ("success", "识别成功"),
                            ("failed", "识别失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="识别状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="识别时间"),
                ),
            ],
            options={
                "verbose_name": "视觉识别记录",
                "verbose_name_plural": "视觉识别记录",
            },
        ),
    ]
