# Generated by Django 5.2.5 on 2026-01-20 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("add", "添加库存"),
                            ("subtract", "减少库存"),
                            ("set", "设置库存"),
                        ],
                        max_length=20,
                        verbose_name="操作类型",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="操作数量")),
                ("reason", models.TextField(blank=True, verbose_name="操作原因")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_operations",
                        to="products.product",
                        verbose_name="商品",
                    ),
                ),
            ],
            options={
                "verbose_name": "库存操作记录",
                "verbose_name_plural": "库存操作记录",
                "ordering": ["-created_at"],
            },
        ),
    ]
