# Generated by Django 5.2.5 on 2026-01-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_stockoperation"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                blank=True,
                help_text="例如：Drink、Snack",
                max_length=50,
                verbose_name="商品分类",
            ),
        ),
    ]
